name: 05 -1 - Event Fillers and Activity Types

on: 
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "running whenever a PR is opened or syncronized AND base branch is main"      
        